export const products = [
  {
    id: "1",
    name: "Caftan Andalou",
    details: "Emerald green, hand embroidery",
    sku: "CAF-001",
    category: "Caftan",
    taille: "M",
    price: 18500,
    stock: 6,
    status: "In stock",
  },
  {
    id: "2",
    name: "Takchita Perlee",
    details: "Ivory set with pearl finishing",
    sku: "TAK-014",
    category: "Takchita",
    taille: "L",
    price: 24000,
    stock: 3,
    status: "Low stock",
  },
  {
    id: "3",
    name: "Caftan Fassi",
    details: "Midnight blue with gold sfifa",
    sku: "CAF-021",
    category: "Caftan",
    taille: "XL",
    price: 31200,
    stock: 8,
    status: "In stock",
  },
  {
    id: "4",
    name: "Jabador Ivoire",
    details: "Two-piece ceremonial set",
    sku: "JAB-007",
    category: "Jabador",
    taille: "S",
    price: 14600,
    stock: 0,
    status: "Out of stock",
  },
  {
    id: "5",
    name: "Ceinture Doree",
    details: "Adjustable belt for festive looks",
    sku: "ACC-032",
    category: "Accessory",
    taille: "Unique",
    price: 2800,
    stock: 12,
    status: "In stock",
  },
  {
    id: "6",
    name: "Babouches Assorties",
    details: "Soft leather with matching trim",
    sku: "ACC-041",
    category: "Accessory",
    taille: "Unique",
    price: 3900,
    stock: 2,
    status: "Low stock",
  },
];
