import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { inter } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col text-caftan-text">
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
